# Generated by Django 4.2.7 on 2023-12-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstz', models.DateTimeField(auto_now=True)),
                ('deviceId', models.IntegerField()),
                ('waterLevel', models.FloatField()),
            ],
        ),
    ]
