# Generated by Django 4.2.7 on 2023-12-18 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereadings',
            name='tstz',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
